#!/bin/bash

echo "Building with OpenFOAM-"$WM_PROJECT_VERSION

version=${WM_PROJECT_VERSION:0:1}
variant=${WM_PROJECT_VERSION:2:1}

dir20=2.0-and-lower
dir21=2.1-2.2
dir23=2.3-and-higher

dir=$dir20
if [ $version -lt 2 ]
then
   dir=$dir20
   dirrm1=$dir21
   dirrm2=$dir23
elif [ $version -gt 2 ]
then
   dir=$dir23
   dirrm1=$dir20
   dirrm2=$dir21
elif [ $version -eq 2 ] && [ $variant -le 0 ]
then
   dir=$dir20
   dirrm1=$dir21
   dirrm2=$dir23
elif [ $version -eq 2 ] && [ $variant -ge 1 ] && [ $variant -le 2 ]
then
   dir=$dir21
   dirrm1=$dir20
   dirrm2=$dir23
elif [ $version -eq 2 ] && [ $variant -ge 3 ]
then
   dir=$dir23
   dirrm1=$dir20
   dirrm2=$dir21
fi



cd src/turbulenceModels/incompressible/LES/
cd GenEddyViscABL
rm GenEddyViscABL.H
rm GenEddyViscABL.C
ln -s $dir/GenEddyViscABL.H ./
ln -s $dir/GenEddyViscABL.C ./
rm -rf $dirrm1 $dirrm2
cd ../

cd KosovicOneEqNBA
rm KosovicOneEqNBA.H
rm KosovicOneEqNBA.C
ln -s $dir/KosovicOneEqNBA.H ./
ln -s $dir/KosovicOneEqNBA.C ./
rm -rf $dirrm1 $dirrm2
cd ../
wmake libso
cd ../../../../

cd src/turbineModels
wmake libso
cd ../../

cd src/finiteVolume
wmake libso
cd ../../

cd applications/utilities/setFieldsABL
wmake
cd ../../../

cd applications/solvers/incompressible/windEnergy/ABLSolver
rm pEqn.H
rm ABLSolver.C
rm Make/options
ln -s $dir/pEqn.H ./
ln -s $dir/ABLSolver.C ./
ln -s ../$dir/options ./Make
rm -rf $dirrm1 $dirrm2
wmake
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/ABLTerrainSolver
rm pEqn.H
rm ABLTerrainSolver.C
rm Make/options
ln -s $dir/pEqn.H ./
ln -s $dir/ABLTerrainSolver.C ./
ln -s ../$dir/options ./Make
rm -rf $dirrm1 $dirrm2
wmake
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/windPlantSolver
rm pEqn.H
rm windPlantSolver.C
rm Make/options
ln -s $dir/pEqn.H ./
ln -s $dir/windPlantSolver.C ./
ln -s ../$dir/options ./Make
rm -rf $dirrm1 $dirrm2
wmake
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/windPlantSolver.ADM
rm pEqn.H
rm windPlantSolver.C
rm Make/options
ln -s $dir/pEqn.H ./
ln -s $dir/windPlantSolver.C ./
ln -s ../$dir/options ./Make
rm -rf $dirrm1 $dirrm2
wmake
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/pisoFoamTurbine
rm pisoFoamTurbine.C
rm Make/options
ln -s $dir/pisoFoamTurbine.C
ln -s ../$dir/options ./Make
rm -rf $dirrm1 $dirrm2
wmake
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/pisoFoamTurbine.ADM
rm pisoFoamTurbine.C
rm Make/options
ln -s $dir/pisoFoamTurbine.C
ln -s ../$dir/options ./Make
rm -rf $dirrm1 $dirrm2
wmake
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/turbineTestHarness
rm Make/options
ln -s ../$dir/options ./Make
rm -rf $dirrm1 $dirrm2
wmake
cd ../../../../../

cd src/openfast7/bin
make
./libmake
cd ../../../

cd src/fastturb
wmake libso
cd ../../

cd applications/solvers/incompressible/windEnergy/windPlantSolverFAST
wmake
cd ../../../../../

