#!/bin/bash


cd src/turbulenceModels/incompressible/LES/
rmdepall
wclean
cd ../../../../

cd src/turbineModels
rmdepall
wclean
cd ../../

cd src/finiteVolume
rmdepall
wclean
cd ../../

cd applications/utilities/setFieldsABL
rmdepall
wclean
cd ../../../

cd applications/solvers/incompressible/windEnergy/ABLSolver
#cd applications/solvers/incompressible/windEnergy/ABLSolver-2.1-and-higher
rmdepall
wclean
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/windPlantSolver
#cd applications/solvers/incompressible/windEnergy/windPlantSolver-2.1-and-higher
rmdepall
wclean
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/windPlantSolverFAST
rmdepall
wclean
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/pisoFoamTurbine
rmdepall
wclean
cd ../../../../../

cd applications/solvers/incompressible/windEnergy/turbineTestHarness
rmdepall
wclean
cd ../../../../../
