#!/bin/bash

# Script to set up a SOWFA working directory separate from the actual
# directory from the git repository.  It follows the directory structure
# of the git repository, but all files are symbolically linked back to 
# the git repository directory.  That way when the git repository files
# are updated, the working directory is automatically updated.  It also
# keeps the compilation files out of the repository directory.

# Matt Churchfield
# National Renewable Energy Laboratory
# 28 October 2014




#SOWFAdir=/home/$USER/bin/OpenFOAM/SOWFA
SOWFAdir=/ifs/dm/cfd/app/OpenFOAM/SOWFA

# Do the recursive copy that symbolically links the files to the source.
cp -rs  $SOWFAdir $WM_PROJECT_USER_DIR
