#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

wmake $targetType turbulenceModels
wmake $targetType incompressible

#------------------------------------------------------------------------------
