#!/bin/bash

# Number of nodes and cores to use
nodes=1
cores=8

# Make the mesh using blockMesh (serial)
blockMesh > log.blockMesh 2>&1

# Decompose the mesh and solution files (serial)
decomposePar > log.decomposePar 2>&1

# Run the solver (parallel)
mpirun -np $(($nodes*$cores)) fastPisoSolver -parallel > log.fastPisoSolver 2>&1
